version: "2"
run:
  build-tags:
    - netgo
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - depguard
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - lll
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: true
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
