name: golangci-lint

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Setup Go
        uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Check formatting
        run: test -z "$(gofmt -l $(find . -name '*.go' -not -path './vendor/*'))"

      - name: Check go.mod
        run: go mod tidy -diff

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          only-new-issues: true
          args: --timeout=5m
